version: '2.3'

services:
  data-validation-tool:
    build: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "/Users/chernan/open-data/tool-data-validation/app:/usr/src/app/app"
      